const array = [
  {
    id: 1,
    thumbnail: "https://i.postimg.cc/g2StrXps/poster-11.jpg",
    title: "Tonight she comes",
    genere: "Terror",
    premiereDate: "invalid",
    stars: 5,
    director: "invalid",
    type: "movie",
    price: 300,
  },
  {
    id: 2,
    thumbnail: "https://i.postimg.cc/1zdd7gYX/poster-12.jpg",
    title: "It",
    genere: "Terror",
    premiereDate: "invalid",
    stars: 8,
    director: "invalid",
    type: "movie",
    price: 300,
  },
  {
    id: 3,
    thumbnail: "https://i.postimg.cc/kXCpHPwQ/poster-13.jpg",
    title: "Joker",
    genere: "Drama",
    premiereDate: "invalid",
    stars: 5,
    director: "invalid",
    type: "movie",
    price: 400,
  },
  {
    id: 4,
    thumbnail: "https://i.postimg.cc/Y0Ksk57w/poster-14.jpg",
    title: "Spider-Man Homecoming",
    genere: "Aventura",
    premiereDate: "invalid",
    stars: 7,
    director: "invalid",
    type: "movie",
    price: 500,
  },
  {
    id: 5,
    thumbnail: "https://i.postimg.cc/Y06ySd2L/poster-15.jpg",
    title: "Buscando a Nemo",
    genere: "Animación",
    premiereDate: "invalid",
    stars: 8,
    director: "invalid",
    type: "movie",
    price: 400,
  },
  {
    id: 6,
    thumbnail: "https://i.postimg.cc/fL0rGw6K/poster-16.jpg",
    title: "John Wick - chapter 2",
    genere: "Acción",
    premiereDate: "invalid",
    stars: 8,
    director: "invalid",
    type: "movie",
    price: 500,
  },
  {
    id: 7,
    thumbnail: "https://i.postimg.cc/5NmRdKkZ/poster-17.jpg",
    title: "Interstellar",
    genere: "Ciencia Ficción",
    premiereDate: "invalid",
    stars: 9,
    director: "Christopher Nolan",
    type: "movie",
    price: 300,
  },
  {
    id: 8,
    thumbnail: "https://i.postimg.cc/Vsnh4k9s/poster-18.jpg",
    title: "The Nun",
    genere: "Terror",
    premiereDate: "invalid",
    stars: 6,
    director: "invalid",
    type: "movie",
    price: 400,
  },
  {
    id: 9,
    thumbnail: "https://i.postimg.cc/8C7KvpPS/poster-19.jpg",
    title: "Jurassic World - Fallen Kingdom",
    genere: "Ciencia Ficción",
    premiereDate: "invalid",
    stars: 9,
    director: "Steven Spielberg",
    type: "movie",
    price: 400,
  },
  {
    id: 10,
    thumbnail: "https://i.postimg.cc/HksPp0qj/poster-20.jpg",
    title: "Harry Potter - and the order of the fenix",
    genere: "Aventura",
    premiereDate: "invalid",
    stars: 7,
    director: "invalid",
    type: "movie",
    price: 500,
  },
  {
    id: 11,
    thumbnail: "https://i.postimg.cc/RFfgPgHp/poster-21.jpg",
    title: "E.T",
    genere: "Aventura",
    premiereDate: "invalid",
    stars: 7,
    director: "Steven Spielberg",
    type: "movie",
    price: 200,
  },
  {
    id: 12,
    thumbnail: "https://i.postimg.cc/jjB8QpLJ/poster-22.jpg",
    title: "The Incredibles",
    genere: "Animacion",
    premiereDate: "invalid",
    stars: 7,
    director: "invalid",
    type: "movie",
    price: 300,
  },
  {
    id: 13,
    thumbnail: "https://i.postimg.cc/3JwN5N87/poster-47.jpg",
    title: "Dragon Ball Z - Saga Saiyans",
    genere: "Animacion",
    premiereDate: "invalid",
    stars: 10,
    director: "invalid",
    type: "anime",
    price: 500,
  },
  {
    id: 14,
    thumbnail: "https://i.postimg.cc/Nj3jHx1f/poster-45.jpg",
    title: "One Punch Man",
    genere: "Animacion",
    premiereDate: "invalid",
    stars: 9,
    director: "invalid",
    type: "anime",
    price: 400,
  },
  {
    id: 15,
    thumbnail: "https://i.postimg.cc/rmJV7X7K/poster-53.jpg",
    title: "The Mandalorian",
    genere: "Ciencia Ficcion",
    premiereDate: "invalid",
    stars: 9,
    director: "invalid",
    type: "serie",
    price: 300,
  },
  {
    id: 16,
    thumbnail: "https://i.postimg.cc/BnLvbzPV/poster-52.jpg",
    title: "Teen Wolf",
    genere: "Suspenso",
    premiereDate: "invalid",
    stars: 7,
    director: "invalid",
    type: "serie",
    price: 300,
  },
  {
    id: 17,
    thumbnail: "https://i.postimg.cc/7hnm4bXg/poster-24.jpg",
    title: "Ready Player One",
    genere: "Ciencia Ficcion",
    premiereDate: "invalid",
    stars: 9,
    director: "invalid",
    type: "movie",
    price: 400,
  },
  {
    id: 18,
    thumbnail: "https://i.postimg.cc/gjsq5Qks/poster-34.jpg",
    title: "The Revenant",
    genere: "Drama",
    premiereDate: "invalid",
    stars: 7,
    director: "invalid",
    type: "movie",
    price: 400,
  },
  {
    id: 19,
    thumbnail: "https://i.postimg.cc/T2014gXC/poster-48.jpg",
    title: "Stranger Things",
    genere: "Suspenso",
    premiereDate: "invalid",
    stars: 8,
    director: "invalid",
    type: "serie",
    price: 500,
  },
  {
    id: 20,
    thumbnail: "https://i.postimg.cc/vTs3C57Y/poster-23.jpg",
    title: "Capitan America - Civil War",
    genere: "Accion",
    premiereDate: "invalid",
    stars: 8,
    director: "invalid",
    type: "movie",
    price: 500,
  },
  {
    id: 21,
    thumbnail: "https://i.postimg.cc/ht5Mck83/poster-33.jpg",
    title: "Wall-E",
    genere: "Animacion",
    premiereDate: "invalid",
    stars: 7,
    director: "invalid",
    type: "movie",
    price: 400,
  },
];

const is_OK = Math.random() > 0.5 ? true : false;

let apiPromise = new Promise((resolve, reject) => {
  if (is_OK > 0.5) {
    setTimeout(() => {
      resolve(array);
    }, 2000);
  } else {
    setTimeout(() => {
      reject("UPS!, Error en el servidor...recargue la página para reintentar");
    }, 4000);
  }
});

export default apiPromise;
