const array = [
  {
    id: 1,
    thumbnail: "https://i.postimg.cc/g2StrXps/poster-11.jpg",
    title: "Tonight she comes",
    genere: "Terror",
    time: "1h 24min",
    premiereDate: 2016,
    stars: 3.9,
    director: "Matt Stuertz",
    sinopsis:
      "Después de que una chica desaparezca, sus amigas y unos extraños van al lugar de la desaparición. Una cabaña en el bosque en la que reirán, beberán, se besarán y sufrirán todas las consecuencias de sus actos.",
    trailer: "https://www.imdb.com/video/vi2824648473/?playlistId=tt5161376&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (1.5).toFixed(2),
  },
  {
    id: 2,
    thumbnail: "https://i.postimg.cc/1zdd7gYX/poster-12.jpg",
    title: "It",
    genere: "Terror",
    time: "2h 15min",
    premiereDate: 2017,
    stars: 7.3,
    director: "Andy Muschietti",
    sinopsis:
      "En el verano de 1989, un grupo de niños víctimas de acoso escolar se une para destruir a un monstruo que cambia de forma, que se disfraza de payaso y se aprovecha de los niños de Derry, su pequeña ciudad de Maine.",
    trailer: "https://www.imdb.com/video/vi1396095257/?playlistId=tt1396484&ref_=tt_pr_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.0).toFixed(2),
  },
  {
    id: 3,
    thumbnail: "https://i.postimg.cc/kXCpHPwQ/poster-13.jpg",
    title: "Joker",
    genere: "Drama",
    time: "2h 2min",
    premiereDate: "2019",
    stars: 8.4,
    director: "Todd Phillips",
    sinopsis:
      "En Gotham, Arthur Fleck, un comediante con problemas de salud mental, es marginado y maltratado por la sociedad. Se adentra en una espiral de crimen que resulta revolucionaria. Pronto conoce a su alter-ego, el Joker.",
    trailer: "https://www.imdb.com/video/vi1723318041/?playlistId=tt7286456&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 4,
    thumbnail: "https://i.postimg.cc/Y0Ksk57w/poster-14.jpg",
    title: "Spider-Man Homecoming",
    genere: "Aventura",
    time: "2h 13min",
    premiereDate: "2017",
    stars: 7.4,
    director: "Jon Watts",
    sinopsis:
      "Peter Parker compagina su vida de estudiante ordinario de instituto en Queens con su alter ego de superhéroe, Spider-Man, y se encuentra tras la pista de una nueva amenaza que merodea por los cielos de Nueva York.",
    trailer: "https://www.imdb.com/video/vi4175083801/?playlistId=tt2250912&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.0).toFixed(2),
  },
  {
    id: 5,
    thumbnail: "https://i.postimg.cc/Y06ySd2L/poster-15.jpg",
    title: "Buscando a Nemo",
    genere: "Animación",
    time: "1h 40min",
    premiereDate: "2003",
    stars: 8.2,
    director: "Andrew Staton & Lee Unkrich",
    sinopsis: "Cuando su hijo es capturado, un tímido pez payaso se embarca en un viaje para traerlo a casa.",
    trailer: "https://www.imdb.com/video/vi2687214105/?playlistId=tt0266543&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.5).toFixed(2),
  },
  {
    id: 6,
    thumbnail: "https://i.postimg.cc/fL0rGw6K/poster-16.jpg",
    title: "John Wick - chapter 2",
    genere: "Acción",
    time: "2h 2min",
    premiereDate: "2017",
    stars: 7.4,
    director: "Chad Stahelski",
    sinopsis:
      "Al regresar al inframundo criminal para pagar una deuda, John Wick descubre que se le ha puesto precio a su cabeza.",
    trailer: "https://www.imdb.com/video/vi1127331353/?playlistId=tt4425200&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 7,
    thumbnail: "https://i.postimg.cc/5NmRdKkZ/poster-17.jpg",
    title: "Interstellar",
    genere: "Ciencia Ficción",
    time: "2h 49min",
    premiereDate: "2014",
    stars: 8.6,
    director: "Christopher Nolan",
    sinopsis:
      "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.",
    trailer: "https://www.imdb.com/video/vi1586278169/?playlistId=tt0816692&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 8,
    thumbnail: "https://i.postimg.cc/Vsnh4k9s/poster-18.jpg",
    title: "The Nun",
    genere: "Terror",
    time: "1h 36min",
    premiereDate: "2018",
    stars: 5.3,
    director: "Corin Hardy",
    sinopsis:
      "Un sacerdote con un pasado maldito y una novicia en el umbral de sus últimos votos son enviados por el Vaticano para investigar la muerte de una joven monja en Rumanía y enfrentarse a una fuerza malévola en forma de monja demoníaca.",
    trailer: "https://www.imdb.com/video/vi2039200537/?playlistId=tt5814060&ref_=tt_pr_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.0).toFixed(2),
  },
  {
    id: 9,
    thumbnail: "https://i.postimg.cc/8C7KvpPS/poster-19.jpg",
    title: "Jurassic World - Fallen Kingdom",
    genere: "Ciencia Ficción",
    time: "2h 8min",
    premiereDate: "2018",
    stars: 6.1,
    director: "J.A. Bayona",
    sinopsis:
      "Cuando el volcán inactivo de la isla empieza a rugir, Owen y Claire organizan una campaña para rescatar a los dinosaurios restantes de este evento de nivel de extinción.",
    trailer: "https://www.imdb.com/video/vi2465250073/?playlistId=tt4881806&ref_=tt_pr_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.0).toFixed(2),
  },
  {
    id: 10,
    thumbnail: "https://i.postimg.cc/HksPp0qj/poster-20.jpg",
    title: "Harry Potter - and the order of the fenix",
    genere: "Aventura",
    time: "2h 18min",
    premiereDate: "2007",
    stars: 7.5,
    director: "David Yates",
    sinopsis:
      "Harry y Dumbledore intentan alertar a la comunidad mágica del retorno de Voldemort, para burla general, y se convierten en el foco de una campaña de descrédito a manos de las autoridades mágicas, mientras una burócrata autoritaria toma las riendas de Hogwarts.",
    trailer: "https://www.imdb.com/video/vi2192310553/?playlistId=tt0373889&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (3.5).toFixed(2),
  },
  {
    id: 11,
    thumbnail: "https://i.postimg.cc/RFfgPgHp/poster-21.jpg",
    title: "E.T",
    genere: "Aventura",
    time: "1h 55min",
    premiereDate: "1982",
    stars: 7.9,
    director: "Steven Spielberg",
    sinopsis:
      "Un niño con problemas se arma de valor para ayudar a un amistoso alienígena a escapar de la Tierra y regresar a su mundo natal.",
    trailer: "https://www.imdb.com/video/vi3090130201/?playlistId=tt0083866&ref_=tt_ov_vi",
    type: "movies",
    price: (2.5).toFixed(2),
  },
  {
    id: 12,
    thumbnail: "https://i.postimg.cc/jjB8QpLJ/poster-22.jpg",
    title: "The Incredibles",
    genere: "Animacion",
    time: "1h 55min",
    premiereDate: "2004",
    stars: 8.0,
    director: "Brad Bird",
    sinopsis:
      "Una familia de superhéroes encubiertos, mientras intentan vivir la tranquila vida suburbana, se ven obligados a entrar en acción para salvar el mundo.",
    trailer: "https://www.imdb.com/title/tt0317705/?ref_=ext_shr_lnk",
    type: "movies",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 13,
    thumbnail: "https://i.postimg.cc/3JwN5N87/poster-47.jpg",
    title: "Dragon Ball Z - Saga Saiyans",
    genere: "Animacion",
    time: "24min/cap",
    premiereDate: "1989",
    stars: 8.9,
    director: "Akira Toriyama",
    sinopsis:
      "Una terrible amenaza acaba de llegar a la tierra, una nave aterriza y un poderoso personaje reclama la presencia de su hermano, Goku. Definiendo si origen saiayin enfrenta a Goku y Piccoro quien ahora prestará ayuda para derrotar esta amenaza. Sin embargo algo mas terrible esta por llegar al planeta tierra.",
    trailer: "https://www.imdb.com/video/vi4248940313/?playlistId=tt0214341&ref_=tt_ov_vi",
    type: "anime",
    stock: 5,
    price: (1.0).toFixed(2),
  },
  {
    id: 14,
    thumbnail: "https://i.postimg.cc/Nj3jHx1f/poster-45.jpg",
    title: "One Punch Man",
    genere: "Animacion",
    time: "24min/cap",
    premiereDate: "2015",
    stars: 8.7,
    director: "Makoto Furukawa",
    sinopsis:
      "La historia de Saitama, un héroe que lo hace por diversión y puede derrotar a sus enemigos con un solo golpe.",
    trailer: "https://www.imdb.com/video/vi3474439449/?playlistId=tt4508902&ref_=tt_ov_vi",
    type: "anime",
    stock: 5,
    price: (1.5).toFixed(2),
  },
  {
    id: 15,
    thumbnail: "https://i.postimg.cc/rmJV7X7K/poster-53.jpg",
    title: "The Mandalorian",
    genere: "Ciencia Ficcion",
    time: "40min/cap",
    premiereDate: "2019",
    stars: 8.7,
    director: "Jon Favreau",
    sinopsis:
      "Los viajes de un cazarrecompensas solitario en los confines de la galaxia, lejos de la autoridad de la Nueva República.",
    trailer: "https://www.imdb.com/video/vi1311228185/?playlistId=tt8111088&ref_=tt_ov_vi",
    type: "series",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 16,
    thumbnail: "https://i.postimg.cc/BnLvbzPV/poster-52.jpg",
    title: "Teen Wolf",
    genere: "Suspenso",
    time: "41min/cap",
    premiereDate: "2011",
    stars: 7.7,
    director: "Jeff Davis",
    sinopsis:
      "Un estudiante medio de instituto y su mejor amigo se ven envueltos en un problema que le hace recibir una mordedura de hombre lobo. Como resultado se encuentran en medio de todo tipo de dramas en Beacon Hills.",
    trailer: "https://www.imdb.com/video/vi3872307481/?playlistId=tt1567432&ref_=tt_ov_vi",
    type: "series",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 17,
    thumbnail: "https://i.postimg.cc/7hnm4bXg/poster-24.jpg",
    title: "Ready Player One",
    genere: "Ciencia Ficcion",
    time: "2h 20min",
    premiereDate: "2018",
    stars: 7.4,
    director: "Steven Spielberg",
    sinopsis:
      "Cuando el creador de una realidad virtual llamada OASIS muere, lanza un reto póstumo a todos sus usuarios para que busquen un huevo de pascua, que dará al que lo encuentre su fortuna y el control de su mundo.",
    trailer: "https://www.imdb.com/video/vi2568140825/?playlistId=tt1677720&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.0).toFixed(2),
  },
  {
    id: 18,
    thumbnail: "https://i.postimg.cc/gjsq5Qks/poster-34.jpg",
    title: "The Revenant",
    genere: "Drama",
    time: "2h 36min",
    premiereDate: "2015",
    stars: 8.0,
    director: "Alejandro G. Iñárritu",
    sinopsis:
      "Un hombre de la frontera que participa en una expedición de comercio de pieles en la década de 1820 lucha por sobrevivir después de ser mutilado por un oso y dado por muerto por los miembros de su propio equipo de caza.",
    trailer: "https://www.imdb.com/video/vi3857035801/?playlistId=tt1663202&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (1.8).toFixed(2),
  },
  {
    id: 19,
    thumbnail: "https://i.postimg.cc/T2014gXC/poster-48.jpg",
    title: "Stranger Things",
    genere: "Suspenso",
    time: "51min/cap",
    premiereDate: "2016",
    stars: 8.7,
    director: "Matt Duffer & Ross Duffer",
    sinopsis:
      "La historia narra la súbita desaparición de un niño en esta ciudad durante la década de los 80, hecho que destapa los extraños sucesos que tienen lugar en la zona, producto de una serie de experimentos que realiza el gobierno. Además, en la ciudad aparecen fuerzas sobrenaturales inquietantes y una niña muy perturbadora.",
    trailer: "https://www.imdb.com/video/vi3269313049/?playlistId=tt4574334&ref_=tt_ov_vi",
    type: "series",
    stock: 5,
    price: (3.0).toFixed(2),
  },
  {
    id: 20,
    thumbnail: "https://i.postimg.cc/vTs3C57Y/poster-23.jpg",
    title: "Capitan America - Civil War",
    genere: "Accion",
    time: "2h 27min",
    premiereDate: "2016",
    stars: 7.8,
    director: "Anthony Russo & Joe Russo",
    sinopsis:
      "La implicación política en los asuntos de los Vengadores causa una ruptura entre Iron Man y el Capitán América.",
    trailer: "https://www.imdb.com/video/vi174044441/?playlistId=tt3498820&ref_=tt_pr_ov_vi",
    type: "movies",
    stock: 5,
    price: (2.5).toFixed(2),
  },
  {
    id: 21,
    thumbnail: "https://i.postimg.cc/ht5Mck83/poster-33.jpg",
    title: "Wall-E",
    genere: "Animacion",
    time: "1h 38min",
    premiereDate: "2008",
    stars: (8.4).toFixed(2),
    director: "Andrew Staton",
    sinopsis:
      "En un futuro lejano, un pequeño robot recolector de residuos se embarca inadvertidamente en un viaje espacial que decidirá en última instancia el destino de la humanidad.",
    trailer: "https://www.imdb.com/video/vi2192703769/?playlistId=tt0910970&ref_=tt_ov_vi",
    type: "movies",
    stock: 5,
    price: (1.5).toFixed(2),
  },
];

const is_OK = Math.random() > 0.1 ? true : false;

const apiPromise = () => {
  return new Promise((resolve, reject) => {
    if (is_OK) {
      setTimeout(() => {
        resolve(array);
      }, 2000);
    } else {
      setTimeout(() => {
        reject("ERROR 404: UPS!, ERROR EN EL SERVIDOR, POR FAVOR ACTUALICE LA PAGINA");
      }, 4000);
    }
  });
};
export default apiPromise;
